config/routes.rb
Rails.application.routes.draw do

  resources :followers do
    collection do
      get 'random'
    end
  end
  resources :tweets
  get 'profile' => 'profile#index'
  patch 'profile' => 'profile#update'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  delegate :gravatar,to: :user

  def as_json(options={})
    super(methods: [:name, :gravatar])
  end

  def name
    user.display_name
  end

  def self.stream_for(current_user_id)
    joins(:user)
    .where(["users.id = :current_user_id or users.id in (
      select user_id from followers
      where followed_by = :current_user_id
      )",{current_user_id: current_user_id}])
        .order(created_at: :desc)
        .all
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def as_json(options={})
    { id: id, name: display_name, gravatar: gravatar }
  end

  def display_name
    first_name.present? ? "#{first_name} #{last_name}" : email
  end

  def gravatar
    hash = Digest::MD5.hexdigest(email)
    "http://wwww.gravatar.com/avatar/#{hash}"
  end

  def self.who_to_follow(current_user_id)
    where(["id != :current_user_id and not exists (
      select 1 from followers
      where user_id = users.id
      and followed_by = :current_user_id
    )", { current_user_id: current_user_id }])
        .order("random()").all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def random
    render json: User.who_to_follow(current_user.id)
  end


  def create
    follower = Follower.create(user_id:     params[:user_id],
                               followed_by: current_user.id)
    render json: follower
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    render json: Tweet.stream_for(current_user.id)
  end

  def create
    tweet = Tweet.create(body: params[:body], user_id: current_user.id)
    render json: tweet
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/index.html.erb
<div id="react"></div>

<%#= react_component('Main', {}, {prerender: true}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClone</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js"></script>
</head>

<div class="right">
  <% if user_signed_in? %>
      Welcome
      <%= link_to current_user.display_name, profile_path %>
      <%= link_to 'logout', destroy_user_session_path, method: :delete %>
  <% else %>
      Please
      <%= link_to 'login', new_user_session_path %>
      or
      <%= link_to 'signup', new_user_registration_path %>
  <% end %>
</div>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>